### ISSUE TITLE
Export gif in 4K resolution?

### ISSUE THREAD

**Issue by tomodian** [kenkawakenkenke/stickfigure-recorder#1]
Hi, this module is just super amazing!
Is there any way to export gif image in 4K resolution (3840 x 2160px)?

**Comment by kenkawakenkenke** [comment]
Great idea, I'll take a look.

==Note for implementor:
gif.js.optimized unfortunately doesn't handle scaling of exports (it respects the size of the [added context](https://github.com/kenkawakenkenke/stickfigure-recorder/blob/main/web/src/components/gif_render_module.js#L65)), so we'll need increase the [temporary canvas size](https://github.com/kenkawakenkenke/stickfigure-recorder/blob/main/web/src/components/gif_render_module.js#L101) and update [paintPose](https://github.com/kenkawakenkenke/stickfigure-recorder/blob/d9701e8bc16c9ede81753a49fe9d7673ebe947d0/web/src/detection/pose_painter.js#L119) to handle scaled draws.
